/** Agents 页视图组件的 props 类型（与组件分离，保持视图文件精简）*/

export interface AgentsOpsModalsProps {
  acknowledgeConflict: any
  adaptLoading: any
  adaptOpen: any
  adaptSuggestions: any
  agentReputation: any
  agentSandbox: any
  agents: any
  applyAdaptation: any
  applyDecay: any
  applyDispatchPreview: any
  assignmentColumns: any
  assignmentLoading: any
  assignments: any
  authorizeAgent: any
  authorizeForm: any
  authorizeOpen: any
  autoExtractExperiences: any
  autoExtractKnowledge: any
  autoResolveConflicts: any
  broadcastAgent: any
  broadcastContent: any
  broadcastOpen: any
  broadcasting: any
  claimTask: any
  claimTaskId: any
  clearStepOverride: any
  collabSubgraph: any
  collaborators: any
  collaboratorsLoading: any
  conflictDetail: any
  conflictDetailOpen: any
  conflictOpen: any
  conflictResolveForm: any
  conflictResolveOpen: any
  conflicts: any
  createExperience: any
  createKnowledgeEntry: any
  crossProjectLoading: any
  crossProjects: any
  crossTasksLoading: any
  deleteExperience: any
  deleteKnowledgeEntry: any
  dispatchCandidateOptions: any
  dispatchPolicyDirty: any
  dispatchPolicySaving: any
  dispatchPreview: any
  dispatchPreviewAgent: any
  dispatchPreviewApplying: any
  dispatchPreviewLoading: any
  dispatchPreviewOpen: any
  dispatchPreviewOptions: any
  dmContent: any
  dmFrom: any
  dmOpen: any
  dmSending: any
  dmTo: any
  drawerOpen: any
  experienceCreateOpen: any
  experienceDetail: any
  experienceDetailOpen: any
  experienceForm: any
  experiences: any
  experiencesLoading: any
  form: any
  ignoreConflict: any
  inboxItems: any
  knowledgeCreateOpen: any
  knowledgeDetail: any
  knowledgeDetailOpen: any
  knowledgeEntries: any
  knowledgeForm: any
  knowledgeLoading: any
  knowledgeSearch: any
  learnFromExperience: any
  loadAdaptSuggestions: any
  loadAssignments: any
  loadConflicts: any
  loadCrossProjectTasks: any
  loadKnowledge: any
  loadSharedExperiences: any
  loadStepEffective: any
  loading: any
  navigate: any
  openConflictDetail: any
  openCrossProject: any
  openExperienceDetail: any
  openKnowledgeDetail: any
  openResolveConflict: any
  openSandboxes: any
  previewDispatchTasks: any
  recTasks: any
  recTasksAgent: any
  recTasksLoading: any
  recTasksOpen: any
  recalculateReputation: any
  reputationHistory: any
  revokeCrossProject: any
  saveDispatchPolicy: any
  scanConflicts: any
  selectedAgent: any
  sendBroadcast: any
  sendDirectMessage: any
  setAdaptOpen: any
  setAdaptSuggestions: any
  setAuthorizeForm: any
  setAuthorizeOpen: any
  setBroadcastAgent: any
  setBroadcastContent: any
  setBroadcastOpen: any
  setClaimTaskId: any
  setConflictDetailOpen: any
  setConflictOpen: any
  setConflictResolveForm: any
  setConflictResolveOpen: any
  setDispatchPolicyDirty: any
  setDispatchPreview: any
  setDispatchPreviewAgent: any
  setDispatchPreviewOpen: any
  setDmContent: any
  setDmFrom: any
  setDmOpen: any
  setDmTo: any
  setDrawerOpen: any
  setExperienceCreateOpen: any
  setExperienceDetailOpen: any
  setExperienceForm: any
  setKnowledgeCreateOpen: any
  setKnowledgeDetail: any
  setKnowledgeDetailOpen: any
  setKnowledgeForm: any
  setKnowledgeSearch: any
  setRecTasks: any
  setRecTasksAgent: any
  setRecTasksOpen: any
  setSharedExperiencesOpen: any
  setStepOverrideForm: any
  setStepOverrideOpen: any
  shareExperience: any
  sharedExperiences: any
  sharedExperiencesLoading: any
  sharedExperiencesOpen: any
  stepEffective: any
  stepOverrideForm: any
  stepOverrideOpen: any
  submitResolveConflict: any
  submitStepOverride: any
  updateDispatchPreviewOptions: any
  validateExperience: any
}

export interface AgentsCollabModalsProps {
  agents: any
  channelActivityTrend: any
  channelCreateOpen: any
  channelForm: any
  channels: any
  channelsOpen: any
  chatChannel: any
  chatInput: any
  chatMessages: any
  chatOpen: any
  chatSending: any
  claimCrossTask: any
  collabInstantiateName: any
  collabInstantiateOpen: any
  collabInstantiateProjectId: any
  collabInstantiating: any
  collabTemplates: any
  collabTemplatesLoading: any
  collabTemplatesOpen: any
  completeSandboxExec: any
  createChannel: any
  createExperience: any
  createProtocol: any
  crossTasks: any
  crossTasksOpen: any
  deleteSandbox: any
  deliberationForm: any
  deliberationOpen: any
  experienceCreateOpen: any
  experienceDetail: any
  experienceDetailOpen: any
  experienceForm: any
  instantiateCollabTemplate: any
  instantiateTemplate: any
  learnFromExperience: any
  loadChannels: any
  loadCollabTemplates: any
  loading: any
  openChat: any
  openCollabInstantiate: any
  openCreateSandbox: any
  openEditSandbox: any
  openExperienceDetail: any
  openProtocolDetail: any
  openSandboxCheck: any
  openSandboxExec: any
  openSandboxExecDetail: any
  openSandboxStart: any
  openSandboxTemplates: any
  openSandboxViolation: any
  protocolCreateOpen: any
  protocolDetail: any
  protocolDetailOpen: any
  protocolForm: any
  protocolRespondMsg: any
  protocolRespondOpen: any
  protocols: any
  protocolsLoading: any
  protocolsOpen: any
  resolveProtocol: any
  respondToProtocol: any
  revokeSandboxExec: any
  sandboxCheckForm: any
  sandboxCheckOpen: any
  sandboxCheckResult: any
  sandboxEditingId: any
  sandboxExecDetail: any
  sandboxExecDetailOpen: any
  sandboxExecOpen: any
  sandboxExecSandboxId: any
  sandboxExecutions: any
  sandboxForm: any
  sandboxFormOpen: any
  sandboxOpen: any
  sandboxStartForm: any
  sandboxStartOpen: any
  sandboxTemplateOpen: any
  sandboxTemplates: any
  sandboxViolationForm: any
  sandboxViolationOpen: any
  sandboxes: any
  selectedAgent: any
  sendChatMessage: any
  setChannelCreateOpen: any
  setChannelForm: any
  setChannelsOpen: any
  setChatChannel: any
  setChatInput: any
  setChatMessages: any
  setChatOpen: any
  setCollabInstantiateOpen: any
  setCollabInstantiateProjectId: any
  setCollabTemplatesOpen: any
  setCrossTasksOpen: any
  setDeliberationForm: any
  setDeliberationOpen: any
  setExperienceCreateOpen: any
  setExperienceDetailOpen: any
  setExperienceForm: any
  setProtocolCreateOpen: any
  setProtocolDetail: any
  setProtocolDetailOpen: any
  setProtocolForm: any
  setProtocolRespondMsg: any
  setProtocolRespondOpen: any
  setProtocolsOpen: any
  setSandboxCheckForm: any
  setSandboxCheckOpen: any
  setSandboxCheckResult: any
  setSandboxExecDetailOpen: any
  setSandboxExecOpen: any
  setSandboxForm: any
  setSandboxFormOpen: any
  setSandboxOpen: any
  setSandboxStartForm: any
  setSandboxStartOpen: any
  setSandboxTemplateOpen: any
  setSandboxViolationForm: any
  setSandboxViolationOpen: any
  setSharedExperiencesOpen: any
  sharedExperiences: any
  sharedExperiencesOpen: any
  submitDeliberation: any
  submitSandboxCheck: any
  submitSandboxForm: any
  submitSandboxStart: any
  submitSandboxViolation: any
}
