/**
 * Agent API — main entry point (re-export shim for backward compatibility).
 *
 * This file provides the `agentsApi` singleton and re-exports all types
 * from submodules. The implementation is split across method modules
 * using the mixin pattern.
 */
import { apiClient } from '../client/index.js'

// ── Re-export all types ──────────────────────────────────────────────
export type {
  AgentStatus,
  AgentKind,
  TaskAssignmentState,
  Pagination,
  Agent,
  TaskAssignment,
  AgentRun,
  TaskEvent,
  PostableTaskEventType,
  PostTaskEventData,
  AgentInboxResult,
  NotificationItem,
  ListNotificationsResult,
  SharedContextEntry,
  RunLogLevel,
  RunLogEntry,
  HandoffTaskData,
  HandoffTaskResult,
  DispatchTasksData,
  DispatchPolicy,
  DispatchAssignment,
  DispatchTasksResult,
  DispatchPreviewCandidate,
  DispatchPreviewAssignment,
  DispatchPreviewTaskCandidates,
  DispatchPreviewUnmatchedTask,
  DispatchPreviewResult,
  ReviewQueueAction,
  ReviewQueueItem,
  ListResult,
  PaginatedResponse,
  AgentQueryParams,
  AssignmentQueryParams,
  TaskAssignmentQueryParams,
  CreateAgentData,
  UpdateAgentData,
  AgentWorkingSchedule,
  AgentWorkingScheduleWindow,
  WorkingScheduleEvaluation,
  WorkspaceAgent,
  CreateWorkspaceAgentRequest,
  UpdateWorkspaceAgentRequest,
  ClaimTaskData,
  ClaimTaskResult,
  UpdateAssignmentData,
} from './types'

export type {
  WorkflowStepItem,
  WorkflowItem,
  WorkflowIntegrationConfig,
  WorkflowStepTestRunResult,
  WorkflowDslExport,
  CreateWorkflowStepData,
  CreateWorkflowData,
  WorkflowStepRunItem,
  WorkflowRunItem,
  RunLogItem,
  WorkflowRunConsoleStep,
  WorkflowRunConsoleSummary,
  WorkflowRunConsoleResult,
  WorkflowStepStat,
  WorkflowStepStats,
  WorkflowStepDurationHistogramItem,
  WorkflowStepDurationHistogram,
  WorkflowRunDurationBucket,
  WorkflowRunDurationPercentiles,
  WorkflowStepFailureRateItem,
  WorkflowStepFailureRate,
  WorkflowStepCofailureKey,
  WorkflowStepCofailureMatrix,
  WorkflowStepRetryItem,
  WorkflowStepRetryTopology,
  WorkflowStepHourlyItem,
  WorkflowStepHourlyDistribution,
  WorkflowFailedStepByDuration,
  WorkflowFailedStepsByDuration,
  WorkflowRunTrendBucket,
  WorkflowRunTrend,
  WorkflowSuccessRateItem,
  WorkflowSuccessRateByWorkflow,
  WorkflowFailureCorrelationAgent,
  WorkflowFailureCorrelation,
  WorkflowFailureCorrelationByStepItem,
  WorkflowFailureCorrelationByStep,
  WorkflowStepBottleneckStep,
  WorkflowStepBottleneckAllStep,
  WorkflowStepBottleneckWorkflow,
  WorkflowStepDependencyBottleneck,
  WorkflowSimilarityPair,
  WorkflowSimilarityWorkflow,
  WorkflowSimilarityMatrix,
  StepDurationBucket,
  StepDurationHistogramStep,
  StepDurationHistogramResult,
  StepBottleneckTimelineStep,
  WorkflowStepBottleneckTimeline,
  WorkflowStructuralComplexityItem,
  WorkflowStructuralComplexity,
} from './workflow-types'

export type {
  AgentProductivityItem,
  AgentProductivity,
  AgentProductivityTrendBucket,
  AgentProductivityTrend,
  AgentProductivityAlertItem,
  AgentProductivityAlerts,
  AgentRunResourceUsageItem,
  AgentRunResourceUsage,
  AgentProductivityWeeklyItem,
  AgentProductivityWeeklyComparison,
  AgentProductivityByKindItem,
  AgentProductivityByKind,
  AgentProductivityHourlyHeatmapAgent,
  AgentProductivityHourlyHeatmap,
  AgentProductivityCalendarHeatmap,
  AgentFailureReasonItem,
  AgentFailureReasons,
  FailureErrorPatternAgent,
  FailureErrorPattern,
  AgentFailureErrorPatterns,
  CapabilityGapItem,
  CapabilityOverclaimItem,
  CapabilityMatchedItem,
  CapabilityGapAgent,
  AgentCapabilityGapAnalysis,
  CapabilityStatus,
  CapabilitySupplyDemandItem,
  AgentCapabilitySupplyDemand,
  AgentCollaborator,
  AgentCollaboratorsResult,
  CollaborationGraphNode,
  CollaborationGraphEdge,
  CollaborationGraph,
  CollaborationTimelineEdge,
  CollaborationTimelineSnapshot,
  CollaborationGraphTimeline,
  TaskAllocationFairnessAgent,
  TaskAllocationLorenzPoint,
  TaskAllocationFairness,
  AgentTaskHandoffPair,
  AgentTaskHandoffStats,
  SkillMatchCandidate,
  SkillMatchingTask,
  AgentSkillMatching,
  ChannelActivityItem,
  ChannelActivityTrend,
  WorkloadForecastAgent,
  AgentWorkloadForecast,
  AgentRunResourceTrendAgent,
  AgentRunResourceTrend,
  KnowledgePropagationNode,
  KnowledgePropagationEdge,
  KnowledgePropagationNetwork,
  ProtocolLatencyType,
  ProtocolDecisionLatency,
  SpecializationEvolutionAgent,
  AgentSpecializationEvolution,
  AgentHealthSubScores,
  AgentHealthItem,
  AgentHealth,
  AgentHealthTrendBucket,
  AgentHealthTrend,
  HealthStateTransitionFlow,
  AgentHealthStateTransitions,
  AgentHealthAlertItem,
  AgentHealthAlerts,
  HealthWeights,
  AgentIdleStage,
  AgentIdleItem,
  AgentIdleRanking,
} from './analytics-types'

export type {
  ExperiencesStats,
  ExperiencesTopReusedItem,
  ExperiencesLowConfidenceItem,
  ExperiencesLowConfidence,
  ExperiencesScatterPoint,
  ExperiencesScatter,
  ExperiencesReuseTrendBucket,
  ExperiencesReuseTrend,
  ExperiencesConfidenceDecayForecast,
  ExperiencesDecayByDomainItem,
  ExperiencesDecayByDomain,
  ExperiencesDecayByTaskTypeItem,
  ExperiencesDecayByTaskType,
  ExperiencesConfidenceBin,
  ExperiencesConfidenceDistribution,
  ExperiencesSourceItem,
  ExperiencesSourceDistribution,
  ExperiencesPropagationChainItem,
  ExperiencesPropagationChain,
  SkillCoverageAgent,
  ExperiencesSkillCoverageRadar,
  ExperiencesDecayAlert,
  AgentExperiencesDecayAlerts,
  CrossProjectAuthEfficiency,
  AgentCrossProjectEfficiency,
} from './experience-types'

export type {
  SandboxExecutionItem,
  SandboxViolationTrendBucket,
  SandboxViolationTrend,
  SandboxViolationByAgentItem,
  SandboxViolationsByAgent,
  SandboxTemplateUsageItem,
  SandboxTemplateUsage,
  ConflictItem,
  ConflictsDashboard,
  ConflictsTrendBucket,
  ConflictsTrend,
  ConflictByAgentItem,
  ConflictsByAgent,
  ConflictStrategyStat,
  ConflictsStrategyStats,
  ConflictsSandboxCorrelationTypeItem,
  ConflictsSandboxCorrelationAgent,
  ConflictsSandboxCorrelation,
  SecurityEventItem,
  SecurityDailyTrendDay,
  SecurityDailyTrend,
  SecurityByAgentItem,
  SecurityByAgent,
  OrchestrationResult,
  OrchestratorLastRun,
  OrchestratorStatus,
  OrchestrationRunItem,
  OrchestratorHistoryResult,
  OrchestratorDailyTrendDay,
  OrchestratorDailyTrend,
  ReputationHistoryPoint,
  ReputationHistory,
} from './sandbox-conflict-types'

// ── API client（组合实现与单例）──────────────────────────────
export { agentsApi } from './agents-client'
export type { AgentsApi } from './agents-client'

// ── Workspace-based agent APIs (from origin) ──────────────────────
export { agentsApi as workspaceAgentsApi } from './agents'
export { agentKeysApi } from './keys'
export { agentSoulApi } from './soul'
export { agentSecretsApi } from './secrets'
export { agentAutomationApi } from './automation'
export { agentInsightsApi } from './insights'

// Workspace Agent types available as WorkspaceAgent (see types.ts)
export type {
  AgentSoulVersion,
  AgentSoulVersionListResponse,
  RollbackAgentSoulRequest,
} from './soulTypes'
export type {
  AgentSecret,
  AgentSecretType,
  AgentSecretScopeType,
  AgentSecretSource,
  AgentSecretListResponse,
  CreateAgentSecretRequest,
  RevealAgentSecretResponse,
  RotateAgentSecretRequest,
  AgentSecretShare,
  AgentSecretShareListResponse,
  CreateAgentSecretShareRequest,
  AgentSecretTargetSelector,
  AgentSecretCollaborationStats,
  AgentSecretCollaborator,
  AgentSecretCollaborationEdge,
  AgentSecretCollaborationResponse,
  RevealSharedAgentSecretResponse,
} from './secretTypes'

export type {
  AgentKey,
  AgentKeyListResponse,
  CreateAgentKeyRequest,
  CreateAgentKeyResponse,
  RevealAgentKeyResponse,
  ConnectLinkResponse,
} from './keyTypes'
export type {
  AgentRunnerConfig,
  UpdateAgentRunnerConfigRequest,
  AgentTrigger,
  AgentTriggerListResponse,
  CreateAgentTriggerRequest,
  UpdateAgentTriggerRequest,
  AgentRun as WorkspaceAgentRun,
  AgentRunListResponse as WorkspaceAgentRunListResponse,
  NotificationChannel,
  NotificationChannelListResponse,
  CreateNotificationChannelRequest,
  UpdateNotificationChannelRequest,
  EffectiveChannelsResponse,
} from './automationTypes'
export type {
  AgentInsightsPagination,
  AgentActivityItem,
  AgentActivityListResponse,
  AgentProjectInsightItem,
  AgentProjectInsightListResponse,
  AgentInteractionInsightItem,
  AgentInteractionInsightListResponse,
  AgentTaskInsightAttempt,
  AgentTaskInsightItem,
  AgentTaskInsightListResponse,
  WorkspaceAgentActivityListResponse,
} from './insightsTypes'
